web_frameworks/Django/adboard/bboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_frameworks/Django/adboard/main/urls.py
from django.urls import path

from .views import index
from .views import other_page

app_name = 'main'
urlpatterns = [
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
]

web_frameworks/Django/adboard/main/models.py
from django.db import models

class Rubric(models.Model):
    name = models.CharField(max_length=20, db_index=True, unique=True, verbose_name='Name')
    order = models.SmallIntegerField(default=0, db_index=True, verbose_name='Order')
    super_rubric = models.ForeignKey('SuperRubric', on_delete=models.PROTECT, null=True, blank=True, verbose_name='SuperRubric')

class SuperRubricManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_rubric_isnull=True)

class SuperRubric(Rubric):
    objects = SuperRubricManager()

    def __str__(self):
        return self.name
    
    class Meta:
        proxy = True
        ordering = ('order', 'name')
        verbose_name = 'SuperRubric'
        verbose_name_plural = 'SuperRubrics'

class SubRubricManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_rubric_isnull=False)

class SubRubric(Rubric):
    objects = SubRubricManager()

    def __str__(self):
        return '%s - %s' % (self.super_rubric.name, self.name)
    
    class Meta:
        proxy = True
        ordering = ('super_rubric__order', 'super_rubric__name', 'order', 'name')
        verbose_name = 'SubRubric'
        verbose_name_plural = 'SubRubrics'


from .utilities import get_timestamp_path

class Bb(models.Model):
    rubric = models.ForeignKey(SubRubric, on_delete=models.PROTECT, verbose_name='Rubric')
    title = models.CharField(max_length=40, verbose_name='Product')
    content = models.TextField(verbose_name='Description')
    price = models.FloatField(default=0, verbose_name='Price')
    contacts = models.TextField(verbose_name='Contacts')
    image = models.ImageField(blank=True, upload_to=get_timestamp_path, verbose_name='Image')
    is_active = models.BooleanField(default=True, db_index=True, verbose_name='Need to output?')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published')
    
    class Meta:
        verbose_name_plural = 'Ads'
        verbose_name = 'Ad'
        ordering = ['-created_at']

web_frameworks/Django/adboard/main/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'main/index.html')

from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template

def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))

web_frameworks/Django/adboard/main/templates/layout/basic.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type"
        content="text/html; charset=utf-8">
        <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %} Main {% endblock %} - Adboard</title>
        {% bootstrap_css %}
        <link rel="stylesheet" type="text/css"
        href="{% static 'main/style.css' %}">
        {% bootstrap_javascript jquery='slim' %}
    </head>
    <body class="container-fluid">
        <header class="mb-4">
            <h1 class="display-1 text-center">Ads</h1>
        </header>
        <div class="row">
            <ul class="col nav justify-content-end border">
                <li class="nav-item">
                    <a class="nav-link" href="#">Registration</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle"
                    data-toggle="dropdown" href="#"
                    role="button" aria-haspopup="true"
                    aria-expanded="false">Profile</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">My ads</a>
                        <a class="dropdown-item" href="#">Change personal data</a>
                        <a class="dropdown-item" href="#">Change password</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Quit</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Delete</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Quit</a>
                </li>
            </ul>
        </div>

        <div class="row">
            <nav class="col-md-auto nav flex-column border">
                <a class="nav-link root"
                href="{% url 'main:index' %}">Main</a>
                <span class="nav-link root font-weight-bold">Property</span>
                <a class="nav-link" href="#">House</a>
                <a class="nav-link" href="#">Warehouses</a>
                <a class="nav-link" href="#">Garages</a>
                <span class="nav-link root font-weight-bold" href="#">Transport</span>
                <a class="nav-link" href="#">Passenger</a>
                <a class="nav-link" href="#">Freight</a>
                <a class="nav-link root" href="{% url 'main:other' page='about' %}">About site</a>
            </nav>
            <section class="col border py-2">
                {% bootstrap_messages %}
                {% block content %}
                {% endblock %}
            </section>
        </div>
        <footer class="mt-3">
            <p class="text-right font-italic">&copy: readers, 2018</p>
        </footer>
    </body>
</html>

web_frameworks/Django/adboard/main/templates/main/about.html
{% extends "layout/basic.html" %}

{% block title %} About site{% endblock %}

{% block content %}
<h2>About site</h2>
<p>Site to publish ads</p>
<p>All rights reserved</p>
{% endblock %}

web_frameworks/Django/adboard/main/templates/main/index.html
{% extends "layout/basic.html" %}

{% block content %}
<h2>Last 10 ads</h2>
{% endblock %}